### ISSUE TITLE
Description

### ISSUE THREAD

**Issue by CreaturePhil** [FakeSloth/buma#2]
We need a good description for buma.

I was thinking something like "Reddit-style forum"...

**Comment by GreysonCode** [comment]
Reddit is pretty recognizable as a forum template, but it has some things that are a little lack-luster (such as no word/character limit, usernames that aren't restricted very closely, and overall plainness). 

If we're going on the idea of how Reddit displays threads and comments, that should be noted, and any differences should be clearly described. My main question here would be "what do you want this to look like in the end?"

**Comment by CreaturePhil** [comment]
Probably similar design of the AlienBlue Reddit Application on iPhone but will be optimize for desktops.

**Comment by margaretjoanmiller** [comment]
A forum similar to Reddit with a much more pleasing interface and without all of the trolls.

**Comment by CreaturePhil** [comment]
I like a description that doesn't involve "Reddit in it"

**Comment by CreaturePhil** [comment]
reddit: "we power awesome communities."

phpbb: "free flat-forum bulletin board software solution that can be used to stay in touch with a group of people or can power your entire website." also, it is "creating communities"

prophpbb: "provides secure, reliable and fast forum hosting for thousands of forums at absolutely no cost."

nodebb: "A better forum platform for the modern web."

**Comment by CreaturePhil** [comment]
buma: "Platform that creates and powers amazing communities".

What do you guys think?

**Comment by margaretjoanmiller** [comment]
@CreaturePhil Pretty good :smile:
