### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by CreaturePhil** [FakeSloth/buma#3]
I think we should use versioning in this project as it helps keep track of what things changed in the larger scope of things. A good example of this is the [express](https://github.com/strongloop/express/blob/master/History.md) repository.

We'll being using [milestones](https://github.com/FakeSloth/buma/milestones) and [CHANGELOG file](https://github.com/FakeSloth/buma/blob/master/CHANGELOG.md).

What do you guys think?

**Comment by CreaturePhil** [comment]
Also just want to point out the use of [labels](https://github.com/FakeSloth/buma/labels)!

**Comment by margaretjoanmiller** [comment]
@CreaturePhil Looks good :)
