### ISSUE TITLE
Reference files in docs

### ISSUE THREAD

**Issue by CreaturePhil** [FakeSloth/buma#6]
Should I reference files in docs? If so, how should I do it? Also is **reference files** a clear enough name? Basically, they are the file relating to the docs. The developer can find the code relating to the docs much easier.

Here are some examples:

> ## Initial Files
> 
> Reference files: [`package.json`](), [`server.js`](), [`config/config.js`]()
> 
> We used `git init` to start a git repository and `npm init` to create a 
> `package.json` file.
> `server.js` will be the main file used and it is the center of the app. It 
> will start the application, loading all dependencies and routes. 
> We also created a `config/config.js` file to hold all our configuration 
> variables.
> ## Model
> 
> Reference file: [`app/models/users.js`]()
> 
> Using `mongoose` allows us to create a schema (aka template) for the user.
> We have the standard email, username, and password fields. `uid` stands for
> username id and it is just a faster way to get usernames by not having to
> worry about letter casing. We use [bcrypt][bcrypt] to hash our passwords 
> because storing passwords in plaintext is not a good idea.
> 
> We also have validation for username to meet certain criteria and make sure
> some fields are unique, we don't want multiple users to have the same 
> username.

**Comment by margaretjoanmiller** [comment]
Sure; looks good :smile: If you want, some alternatives to "reference file" are "working file," and, "relevant file(s)."

**Comment by CreaturePhil** [comment]
Ah, cool! Then I'll add it in.

Also, right now I'm in pain due to thoughts about implementing the authentication system with Angular.js and JSON Web Tokens haha :laughing: :disappointed:. I should just start implementing it right away instead of thinking of how it all works and fits together in my head.

**Comment by CreaturePhil** [comment]
> Take any Angular controller and you'll be constantly jumping back and forth between ng-\* attributes and your controller - they go together.

^ This is Angular 1.0. Should we in this project jump into Angular 2.0. It is still in alpha though but I like to be a hipster.
